### ISSUE TITLE
How to add width and height?

### ISSUE THREAD

**Issue by rafialikhan** [JamesGuthrie/angular-schema-form-signature#1]
How do we pass the height and width?

Tried

`{
                              key: 'signature',
                              type: 'signature'
                              height: '200px',
                              width: '500px'
}`

Does not work.

**Comment by JamesGuthrie** [comment]
That wasn't officially supported yet, and it had a bug. I've fixed it now so that your declaration should work, try using version `0.1.2`. As the parameters are being passed to [angular-signature](https://github.com/legalthings/angular-signature) you should drop the 'px' and just pass the numeric values.

**Comment by rafialikhan** [comment]
Thanks this works now. Had forked it and made the changes, but better to use your version always.
